### ISSUE TITLE
"Boot qube from DISK or block device" in Qube Settings doesn't work in 4.3

### ISSUE THREAD

**Issue by faklapant23** [QubesOS/qubes-issues#10164]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.3 rc1

### Brief summary

"Boot qube from DISK or block device" in Qube Settings doesn't work Qubes OS 4.3 (clean install, dom0 updated to the latest testing updates).
Booting with ISO work fine from dom0 terminal using qvm-start with ISO from exposed loop device, so it's a problem with GUI.

### Steps to reproduce

Try to boot from ISO in a standalone qube not based on a template using Qube Settings GUI.
The ISO is stored in the app qube based on a default debian-12-xfce template with latest updates.
When you go to the standalone qube's Qube Settings -> Advanced -> press on "Boot qube from DISK or block device" -> from file in qube -> select the qube and press a ... button -> it'll open a file selection dialog and you choose the ISO from this qube.
After confirming the chosen file, it'll display a window with this error:

```
[Dom0] Failed to display file selection dialog
Check if the qube storage can be started and has a file manager installed.
```

The same problem happens when using different ISOs.

Another issue is with booting "from existing block device".
Created loopback device with ISO in the qube:
```
sudo losetup -f /path/to/iso
```
Then try to boot it from the GUI, but choosing "from existing block device" instead of "from file in qube" this time.
It doesn't work as well.
After choosing block device and pressing OK, the Qube Settings closes, but the qube with this image doesn't start.

### Expected behavior

It's possible to boot a standalone qube not based on a template with ISO using GUI.

### Actual behavior

Both booting "from existing block device" and "from file in qube"  in GUI don't work.

**Comment by andrewdavidwong** [comment]
Possibly related: #4438

**Comment by ArrayBolt3** [comment]
> Then try to boot it from the GUI, but choosing "from existing block device" instead of "from file in qube" this time.
> It doesn't work as well.
> After choosing block device and pressing OK, the Qube Settings closes, but the qube with this image doesn't start.

Can reproduce reliably on R4.3.0 rc3:

* Ensure sys-usb is running
* Insert into the system a USB drive that has previously had a hybrid-bootable ISO (such as Kicksecure's) flashed to it, ensure it shows up in the Qubes Devices widget
* Create a new standalone HVM qube named (for instance) `ks-iso`, ensure that both "Launch Qube Settings after creation" and "Install system from device (also available from settings)" are unchecked before clicking "Create new qube"
* In Qube Manager, click on the new HVM, and click Settings
* In the Basic tab, set system storage max size to 32 GB
* In the Advanced tab, set initial memory to 4000 MB and disable memory balancing
* Click "Apply"
* Click "Boot qube from DISC or block device"
* In the popup window, click "from existing block device"
* Select `sys-usb:sda:<big long string here>` as the device
* Click "OK"

Expected result: A notification should appear that "ks-iso" is starting, then a window for the VM's console should appear shortly thereafter.

Actual result: Both the "Boot ks-iso from device" and "Settings: ks-iso" windows vanish, then nothing happens thereafter. No notification, no VM console. Complete silent failure from a typical end-user standpoint.

If I run `qubes-qube-manager` in a terminal, then attempt to boot from the block device, I see the line `Error: Got empty response from qubesd. See journalctl in dom0 for details.` appear after clicking "OK" in the last step of the reproduction steps. Upon running `journalctl --boot -u qubesd` in dom0, I see the following line at the end of the log (typed manually, may contain typos):

```
Nov 27 00:14:155 dom0 qubesd[3313]: WARNING: protocol error for call b'admin.vm.device.block.Assign'+b'sys-usb+sda:154b:1006:071C4983299C2216:u080650:1.0:*' (b'dom0' → b'ks-iso') with payload of 184 bytes
```

**Comment by ben-grande** [comment]
@faklapant23 @ArrayBolt3 Fixed in:

- https://github.com/QubesOS/qubes-core-admin/pull/759

?

You can also emulate the GUI:

```python3
import qubesadmin, qubesmanager.utils
app = qubesadmin.Qubes(); domains = app.domains
qube = domains["sys-firewall"]
qubesmanager.utils.get_path_from_vm(qube, "qubes.SelectFile")
```

If the above doesn't log an exception, see following validations that you may try to run manually.

https://github.com/QubesOS/qubes-manager/blob/0ca0407c19d5653bcf152d8ff634586cb5784a3d/qubesmanager/utils.py#L460

Validations:

- strips whitespace on edges
- has 512 max length
- has a regex for allowed characters
- must be ascii encoded
- blocks path transversal and possibly symlinks

**Comment by ben-grande** [comment]
[@faklapant23](https://github.com/faklapant23) [@ArrayBolt3](https://github.com/ArrayBolt3) please retest so this issue can be resolved.

**Comment by ArrayBolt3** [comment]
Will put on my todo list now. I'll have a daily-driver Qubes machine in a couple of days most likely, so I should be able to test this then.

**Comment by ArrayBolt3** [comment]
@ben-grande The issue I ran into with installing qubes from a physical block device is not solved; the steps listed [above](https://github.com/QubesOS/qubes-issues/issues/10164#issuecomment-3584362522) still have the same "silent failure" effect, and the same error message in the journal can still be found. I made sure that my version of `qubes-core-dom0` is new enough that I have the code from the PR listed above present on the system, and I have all testing updates installed (and rebooted after installing them to make sure they're actively being used).

It looks like the fix above is mostly for booting from image files present in other qubes; I did not test this yet. Maybe the issue about device boot failing should be split into a separate bug report?

**Comment by ben-grande** [comment]
> If I run `qubes-qube-manager` in a terminal, then attempt to boot from the block device, I see the line `Error: Got empty response from qubesd. See journalctl in dom0 for details.` appear after clicking "OK" in the last step of the reproduction steps. Upon running `journalctl --boot -u qubesd` in dom0, I see the following line at the end of the log (typed manually, may contain typos):
> 
> ```
> Nov 27 00:14:155 dom0 qubesd[3313]: WARNING: protocol error for call b'admin.vm.device.block.Assign'+b'sys-usb+sda:154b:1006:071C4983299C2216:u080650:1.0:*' (b'dom0' → b'ks-iso') with payload of 184 bytes
> ```

Do you have earlier logs related to this failure? The user journal might also indicate the issue.



> It looks like the fix above is mostly for booting from image files present in other qubes; I did not test this yet. Maybe the issue about device boot failing should be split into a separate bug report?

Yes, it appears you issue is different.

**Comment by SuzanneSoy** [comment]
Workaround:

Use `qvm-start --cdrom disp1234:loop0 name-of-vm-to-boot`, hopefully using the same format as `qvm-device block list` will work for USB devices too and not just loopback devices (I didn't test with a real USB device).

----------

I've reproduced this issue trying to boot a qube from a loopback device (rather than a device exported by `sys-usb`), it seems like the problem bug occurs because `VMBootFromDeviceWindow` uses `str(device)` to populate the drop-down list [here](https://github.com/QubesOS/qubes-manager/blob/f7017b45be8d810d7b49f606afad6912b46e33d6/qubesmanager/bootfromdevice.py#L131) and uses `.currentText()` [here](https://github.com/QubesOS/qubes-manager/blob/f7017b45be8d810d7b49f606afad6912b46e33d6/qubesmanager/bootfromdevice.py#L74) to get the `cdrom_location`.

```
        for domain in self.qubesapp.domains:
            ...
                for device in domain.devices["block"]:
                    device_choice.append((str(device), device))
...
            self.cdrom_location = self.blockDeviceComboBox.currentText()
```

That `device` variable is a [`DeviceInfo`](https://github.com/QubesOS/qubes-core-admin-client/blob/bdbbe5f2a4c659189bdb8ccb9f5122ab77b8d4a4/qubesadmin/device_protocol.py#L895) which inherits its `__str__` from [`VirtualDevice.__str__`](https://github.com/QubesOS/qubes-core-admin-client/blob/bdbbe5f2a4c659189bdb8ccb9f5122ab77b8d4a4/qubesadmin/device_protocol.py#L542-L543), and includes the `device_id` which seems to be a sequential number prefixed with a colon for loopback devices, e.g. `:0`, and seems to be `154b:1006:071C4983299C2216:u080650:1.0:*` for the USB device in this bug report, instead of the more descriptive `loop0` or `sda`.

```
class VirtualDevice:
    ...
    def __str__(self) -> str:
        return f"{self.port}:{self.device_id}"
    ...
class DeviceInfo(VirtualDevice):
    ...
```

However, [`Port.__str`](https://github.com/QubesOS/qubes-core-admin-client/blob/bdbbe5f2a4c659189bdb8ccb9f5122ab77b8d4a4/qubesadmin/device_protocol.py#L301) already includes that `loop0` i.e. the `port_id`, prefixed with the `backend_name` e.g. the VM name `disp1234`.

```
    def __str__(self) -> str:
        return f"{self.backend_name}:{self.port_id}"
```

As a result, the VM is started via [admin_utils.start_expert](https://github.com/QubesOS/qubes-manager/blob/f7017b45be8d810d7b49f606afad6912b46e33d6/qubesmanager/settings.py#L1395-L1397)
```
            admin_utils.start_expert(
                domain=self.vm, drive="cdrom:" + boot_dialog.cdrom_location
            )
```
or with the currently-shipped line below
```
            qvm_start.main(["--cdrom", boot_dialog.cdrom_location, self.vm.name])
```
using a `boot_dialog.cdrom_location` which is `disp1234:loop0::0` instead of `disp1234:loop0`. Notice the extra `:0` which is the `device_id`, itself separated by a `:` from what we want, hence the trailing `::0`. 

The command `qvm-start --cdrom disp1234:loop0 name-of-vm-to-boot` seems to expect a block device ID in the same format as that produced by [qvm-ls](https://github.com/QubesOS/qubes-core-admin-client/blob/bdbbe5f2a4c659189bdb8ccb9f5122ab77b8d4a4/qubesadmin/tools/qvm_device.py#L92)
```
        self.ident = "{!s}:{!s}".format(device.backend_domain, device.port_id)
```

The new `admin_utils.start_expert` utility might accept a different format but I can't test that given that that method is not available in the currently-shipped version of the code. If it does accept a different format, it might be worth trying to replace the `str()` in `device_choice.append((str(device), device))` to use `repr()` instead, given that the `__repr__` of `DeviceInfo` inherited from `VirtualDevice` produces `disp1234+loop0::0` which is a format I've seen appear elsewhere in the `syslog` while debugging this.

Not a full fix but hope this helps.

**Comment by SuzanneSoy** [comment]
P.S. here are some quick steps to reproduce with a loopback device, helped me iterate quickly:
```
vm_to_create="a_vm_name"
vm_disc_image="disp1234"
qvm-create --class StandaloneVM --label red "$vm_to_create"
qvm-run "$vm_disc_image" dd if=/dev/zero of=/tmp/empty-disk-image bs=1M count=128
qvm-run "$vm_disc_image" sudo losetup -f --show /tmp/empty-disk-image

qvm-start --cdrom "$vm_disc_image:loop0" "$vm_to_create"
```
VM starts and immediately shuts down

```
qubes-qube-manager
```
Right-click on a_vm_name -> Settings -> Advanced -> Boot qube from DISC or block device -> from existing block device -> `disp1234:loop0::0`.

The window closes immediately, in the terminal we see:
```
Error: Got empty response from qubesd. See journalctl in dom0 for details.
```

**Comment by ben-grande** [comment]
I have the latest development version:
```
% rpm -qf /usr/lib/python3.13/site-packages/qubesadmin/utils/__init__.py
python3-qubesadmin-4.4.0-1.33.fc41.noarch
```

Ran your reproduction steps (thanks, that is very important, please always do so).
```
vm_to_create="test-disk"
vm_disc_image="disp8207"
```
```
qvm-create --class StandaloneVM --label red "$vm_to_create"
qvm-run "$vm_disc_image" dd if=/dev/zero of=/tmp/empty-disk-image bs=1M count=128
qvm-run "$vm_disc_image" sudo losetup -f --show /tmp/empty-disk-image
qvm-start --cdrom "$vm_disc_image:loop0" "$vm_to_create"
```
```
Running 'dd' on disp8207
Running 'sudo' on disp8207
```

MIssing `-p, --pass-io` qvm-run arg to `losetup --show`:
```
% qvm-run -p "$vm_disc_image" sudo losetup -f --show /tmp/empty-disk-image
/dev/loop0
```

```
Jul 27 09:13:14 dom0 qubesd[1094580]: DEBUG: [MainProcess __init__.respond:468] app: received call b'admin.vm.device.block.Assign'+b'disp8207+loop0+_' (b'dom0' → b'test-disk') with payload of 151 bytes
```

Didn't fail, qube started, and shutdown.

```
$ qvm-block list
BACKEND:DEVID   DESCRIPTION                                              USED BY
disp8207:loop0  Block_Storage: hosted by disp8207 /tmp/empty-disk-image
disp8207:loop1  Block_Storage: hosted by disp8207 /dev/loop0
```

---

> Right-click on a_vm_name -> Settings -> Advanced -> Boot qube from DISC or block device -> from existing block device -> `disp1234:loop0::0`.

Qubesd journal:
```
qubesd[792866]: WARNING: [MainProcess __init__.respond:492] app: failed call b'admin.vm.device.block.Assign'+b'disp8207+loop0++0+_' (b'dom0' → b'test-disk') with payload of 154 bytes due to ProtocolError('Got device from port: loop0::0 when expected port: loop0.')
```

Qube Manager process:
```python3
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/qubesmanager/settings.py", line 1395, in boot_from_cdrom_button_pressed
    admin_utils.start_expert(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        domain=self.vm, drive="cdrom:" + boot_dialog.cdrom_location
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/qubesadmin/utils/__init__.py", line 505, in start_expert
    domain.devices["block"].assign(drive_assignment)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/qubesadmin/devices.py", line 126, in assign
    self._add(assignment, "assign")
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/qubesadmin/devices.py", line 158, in _add
    self._vm.qubesd_call(
    ~~~~~~~~~~~~~~~~~~~~^
        None,
        ^^^^^
    ...<2 lines>...
        assignment.serialize(),
        ^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/qubesadmin/base.py", line 107, in qubesd_call
    return self.app.qubesd_call(dest, method, arg, payload,
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        payload_stream)
        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/qubesadmin/app.py", line 928, in qubesd_call
    return self._parse_qubesd_response(return_data)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/qubesadmin/base.py", line 141, in _parse_qubesd_response
    raise exc_class(format_string, *args)
qubesadmin.exc.ProtocolError: Got device from port: loop0::0 when expected port: loop0.
```

I then opened Qube Manager again the in the "Boot qube dialog" -> "from file in qube" -> "disp807" -> typed "loop0" -> "OK" and it didn't raise exceptions. I also typed only "loop0" later and it also didn't raise exceptions, the API call made is the same from `qvm-start` I pasted above.
