### ISSUE TITLE
Network manager/applet on fedora-24 templates now has issues when saving connections

### ISSUE THREAD

**Issue by tonsimple** [QubesOS/qubes-issues#2584]
#### Qubes OS version (e.g., `R3.2`):

R 3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

Fedora-24 after all updates are applied (does not happen if reinstalled and NOT updated)

---

### Expected behavior:
When a  Wi Fi connection is added, it is saved across VM reboots

### Actual behavior:
VM reboot wipes out wifi connections 
No files are added in /rw/config/NM-system-connections

### Steps to reproduce the behavior:
Install a fresh fedora-24 template, and apply all updates.
Shut down the template.
Use it with a netvm (I'm bound to using fedora because building driver module for debian-8 right now is too much pain)

Connect to a wifi network or add it manually via edit connection interface

Try editing the newly created connection.

Save all changes.

Reboot Net-VM

At this point I observe loss of saved connection (network manager can't save connections for some reason)

ADDITIONAL INFORMATION: if the file for the connection was already present in /rw/config/NM-system-connections (I've created some wifi connections on this machine before issue arose) then changes done DO get saved in it.

### General notes:
So far I'm working around by manually creating wifi connections in /rw/config/NM-system-connections (fortunately I had a couple connections there before this issue arose, so I can use those files as "templates") via "sudo gedit", copy-paste from existing connection files, and manual tweaking.

P.S.: I have tried restoring netvm from backup (delete netvm manually, then restore from backup) and the issue persists as long as "fully updated" fedora-24 template is used.

---

**Comment by tasket** [comment]
After it undergoes a significant upgrade, NM sometimes has issues with config schemas produced by older versions. A different issue I had with NM not seeing config changes was resolved by wiping the config to start anew; I did this by creating a new netvm.

**Comment by marmarek** [comment]
Do you have old and new configs for comparing?

**Comment by tonsimple** [comment]
@marmarek 
@tasket 
I only have my old configs, the netvm seems unable to create new ones.

I tried to create a "new" fedora netvm from a template but issue seemed to persist there.

I'll try again and report back.

**Comment by tonsimple** [comment]
@marmarek 
@tasket 

Issue persists for me when creating a "clean" netvm from a freshly installed fedora-24 template

1.Have a reinstalled fedora 24 templates 
2. Install all the latest updates for template
3. create new net-vm from template
Issue arises.

**Comment by tasket** [comment]
@tonsimple 
FWIW, I have been using NM 1.4 for a while now and it works fine. This is the version in Debian 9 and Fedora 25, so I'm thinking upgrading your template to fedora 25 might be a workaround.

**Comment by dmoerner** [comment]
Hm, I am also hitting this bug on a fresh install of Qubes with Fedora 24 templates. One of my wifi passwords (wpa-psk) has been stored, another (WPA2 Enterprise with PEAP) has not. 

I see a number of people claiming on the internet (https://wiki.archlinux.org/index.php/NetworkManager#Using_Gnome-Keyring) that network-manager stores passwords in gnome-keyring if they are only made available to one user, and in /etc/NetworkManager/system-connections (symlink to /rw/config/NM-system-connections on Qubes) if they are made available to all users. 

That workaround doesn't work for me: The password that is stored, and saved in system-connections, is only available for this user. And if I change the settings for the other network that is not stored such that it is made available for all users, it still isn't stored.

Still, even if that workaround isn't correct, it does seem like the problem is most likely that gnome-keyring is sometimes being used to store passwords, and this is not being saved anywhere to persist through VM restarts.

**Comment by thargoid0815** [comment]
It's a glitch in the NetworkManager configuration.

In the TemplateVMs (fedora-24, fedora-25) change
/etc/NetworkManager/NetworkManager.conf and add the 'keyfile' plugin, e.g.:
[main]
plugins=ifbt,keyfile


The changes have to be made to the TemplateVM on which sys-net is based on.

**Comment by dmoerner** [comment]
Thank you, @thargoid0815. That fixed the problem for me.

**Comment by marmarek** [comment]
Thanks @thargoid0815 for debugging this. I guess it works on fedora-23  template upgraded to fedora-24 (or later). There is already [a script](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/network/network-manager-prepare-conf-dir#L17) to make this change in `/etc/NetworkManager/NetworkManager.conf`, but it assume that `plugins` option is there, while in fedora-24, it is commented out by default... Also, last time I've checked, it wasn't possible to specify plugins in `/etc/NetworkManager/conf.d/*.conf` - the setting was silently ignored.

**Comment by dmoerner** [comment]
PR with proposed fix: https://github.com/QubesOS/qubes-core-agent-linux/pull/45

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
