### ISSUE TITLE
Installer parses and modifies pre-existing partitions even if given disk is not selected for installation

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2835]
#### Qubes OS version (e.g., `R3.2`):

R3.2, R4.0

--

### Expected behavior:

Installer ask the user what disks should be used for installation and only modify selected disks, and only in a way configured in installer (do not touch partition not used as installation target).
Actually main anaconda screen contains phrase: "We won't touch your disks until you click 'Begin Installation'.". This is not true.

### Actual behavior:

Before showing main anaconda screen, it "probe for storage". This include:
 - Running fsck on all found partitions, LVM volumes etc. According to [code comment](https://github.com/rhinstaller/blivet/blob/2.1-devel/blivet/formats/fs.py#L320), it is to obtain reliable information about possible partition resize
 - [Mounting each found Linux partition, and parse some files there](https://github.com/rhinstaller/blivet/blob/2.1-devel/blivet/osinstall.py#L117-L223) (/etc/fstab, /etc/os-release). This is supposedly also to provide more information about those partitions...

### General notes:

Besides performance impact, this have serious other implications:
 - can lead to data loss - for example if some of those partitions are signed with dm-verity (like in Chromium OS, or Heads), or belongs to hibernated system
 - security aspect: previously installed, malicious OS can try to compromise some of those parses by leaving specifically crafted data on disk

#### Related issues:

Upstream issues:
 - https://bugzilla.redhat.com/show_bug.cgi?id=1170803 (about modifying disks without consent) - accepted as a blocker for Fedora 27, after sitting there for over 2 years)
 - https://bugzilla.redhat.com/show_bug.cgi?id=1374983 (about performance)
 - https://bugzilla.redhat.com/show_bug.cgi?id=1268700 (about performance)

### Proposed half-solution

Modifying this part of installer from downstream distribution position is quite hard - require forking some more packages. Until upstream issue got fixed, add appropriate info to installation guide. Something like:

>Warning: installer will try to access all existing partitions, running fsck there and mounting them. It is recommended to physically disconnect unrelated disks during the installation. If installation target contain potentially compromised system, it is also recommended to wipe the disk before launching the installer.

**Comment by andrewdavidwong** [comment]
Oh, wow. I agree with your "proposed half-solution." I'd just add that we want to stress that this is an upstream bug.

**Comment by andrewdavidwong** [comment]
Added a warning to the installation guide.

**Comment by andrewdavidwong** [comment]
Updated the documentation warning to specify that the issue affects only 3.2 and is fixed in 4.0.

**Comment by marmarek** [comment]
The fix prevent calling fsck, but do not prevent mounting partitions.

**Comment by andrewdavidwong** [comment]
@marmarek: If you expect that this will be fixed before the 4.0 stable release, I will leave the documentation as-is (stating that the issue is fixed in 4.0). Otherwise, I can update the documentation to clarify that it is only partially fixed in 4.0.

**Comment by marmarek** [comment]
This is still an issue in R4.1 installer. Additionally, if mount fails, installer crashes.
Failed test: https://openqa.qubes-os.org/tests/2799
```
04:02:17,475 WRN storage: IGNORED:          Caught exception, continuing.
04:02:17,476 WRN storage: IGNORED:          Problem description: mount of sda1 as ext4 failed
04:02:17,476 WRN storage: IGNORED:          Begin exception details.
04:02:17,478 WRN storage: IGNORED:              Traceback (most recent call last):
04:02:17,478 WRN storage: IGNORED:                File "/usr/lib64/python3.7/site-packages/pyanaconda/storage/osinstall.py", line 326, in _find_existing_installations
04:02:17,479 WRN storage: IGNORED:                  device.format.mount(options=options, mountpoint=sysroot)
04:02:17,479 WRN storage: IGNORED:                File "/usr/lib/python3.7/site-packages/blivet/threads.py", line 53, in run_with_lock
04:02:17,479 WRN storage: IGNORED:                  return m(*args, **kwargs)
04:02:17,479 WRN storage: IGNORED:                File "/usr/lib/python3.7/site-packages/blivet/formats/fs.py", line 761, in mount
04:02:17,480 WRN storage: IGNORED:                  return self.setup(**kwargs)
04:02:17,480 WRN storage: IGNORED:                File "/usr/lib/python3.7/site-packages/blivet/threads.py", line 53, in run_with_lock
04:02:17,480 WRN storage: IGNORED:                  return m(*args, **kwargs)
04:02:17,481 WRN storage: IGNORED:                File "/usr/lib/python3.7/site-packages/blivet/formats/__init__.py", line 609, in setup
04:02:17,481 WRN storage: IGNORED:                  self._setup(**kwargs)
04:02:17,481 WRN storage: IGNORED:                File "/usr/lib/python3.7/site-packages/blivet/threads.py", line 53, in run_with_lock
04:02:17,482 WRN storage: IGNORED:                  return m(*args, **kwargs)
04:02:17,482 WRN storage: IGNORED:                File "/usr/lib/python3.7/site-packages/blivet/formats/fs.py", line 559, in _setup
04:02:17,482 WRN storage: IGNORED:                  self._mount.do_task(chrooted_mountpoint, options=options)
04:02:17,482 WRN storage: IGNORED:                File "/usr/lib/python3.7/site-packages/blivet/tasks/fsmount.py", line 125, in do_task
04:02:17,483 WRN storage: IGNORED:                  raise FSError("mount failed: %s" % rc)
04:02:17,483 WRN storage: IGNORED:              blivet.errors.FSError: mount failed: 32
04:02:17,483 WRN storage: IGNORED:          End exception details.
```
("IGNORED" above seems to be a lie)

**Comment by adrelanos** [comment]
My setup was:

* **A)** Qubes R4.0 on internal SSD.
* **B)** Qubes R4.1 installer on USB SSD (1).
* **C)** Another USB SSD (2) was supposed to be installation target for Qubes R4.1 for testing purposed (hardware compatibility testing, bug reporting, etc.). The contents of USB SSD (2) was an older [full raw disk backup](https://www.whonix.org/wiki/Raw_Disk_Backup) of my internal SSD.

Therefore disk uuid of harddisk A and C was the same.

Qubes installer (running from drive B) didn't allow me to install to drive C. Complained about duplicate disk uuids. Qubes installer was scanning disk A) even though it shouldn't have been involved.

I had to delete the partition table of drive C before I could proceed.
