### ISSUE TITLE
installation stop on "installing storaged.x86_64 (635/998)" every time I run the installation of Qubes-os R4 rc1

### ISSUE THREAD

**Issue by adavida** [QubesOS/qubes-issues#3198]
#### Qubes OS version:
Qubes os R4 rc1

### Steps to reproduce the behavior:
I launch the installation of qubes-os on my pc 

### Expected behavior:
finish install

### Actual behavior:
everything is blocked, except the mouse cursor that I pee still closet.
but nothing happens when I click, or make a key combination.
the animation next to the message freezes.

I tested several faith to install qubes R4rc1, and always the same blocking

### General notes:
my pc is alienware 15r3, with ssd intel 600p

---

**Comment by adavida** [comment]
I got to install Qubes-os R4 rc2 release today

I do not know if it is R4 r2 qubes-os that corrects the problem. or that I added an option - modprobe.blacklist = bochs_drm - at boot (I'm in EFI) in the xen.efi file
I have the same problem as here: https://www.qubes-os.org/doc/linux-hvm-tips/
although the context is different, I also tried.
but, anaconda was really slow in being animations, 1fps or less

**Comment by andrewdavidwong** [comment]
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by WolfBlitz** [comment]
Laptop: MSI GS63VR
This problem exists in RC1.0 RC 2.0 RC 3.0 
Installation stuck at installing "storaged".
Tried both uefi mode and legacy mode, both failed.
Tried adding modprobe.blacklist = bochs_drm in efi conf and replace in grub, still failed.
Tried with/without luks, both failed
Tried lvm and btrfs, both failed
Thanks if someone could fix this issue, in great hurry...

**Comment by WolfBlitz** [comment]
I too have the problem described previpusly
https://www.qubes-os.org/doc/linux-hvm-tips/
However in legacy mode, it doesn't work using modprobe.blacklist = bochs_drm, and installer won't start graphical mode…
In efi mode, it went into graphical mode but still stuck at storaged.

**Comment by ampanasiuk** [comment]
Still with us with 4.0rc3. Booting through UEFI, using the ISO image, written into a partition on the hard drive or onto an USB stick. Tried with all and with none additional components selected for installation. Tried with encrypted LVM and with non-encrypted regular ext4 target partition. Target partition 34GiB.
smartctl -a:
Device Model:     WDC WDS120G1G0B-00RC30
Firmware Version: Z3311000
User Capacity:    120,034,123,776 bytes [120 GB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    Solid State Device
Form Factor:      M.2

**Comment by ampanasiuk** [comment]
Worked around it by writing the iso onto a partition a USB stick, extracting the EFI directory into a new FAT partition on the same stick, editing EFI/BOOT/xen.cfg to add rd.driver.blacklist=nouveau nouveau.modeset=0 video=vesa:off to one of the "kernel" lines and boot from the FAT partition.
Graphic card is nVIDIA GTX1060

**Comment by marmarek** [comment]
Do you have also integrated graphic card?

**Comment by ampanasiuk** [comment]
Tak, intela (i udało mi się poprawić sytuację zabraniając używania modułu
Xorg nouveau)

--AP

**Comment by yilmi** [comment]
Used a similar workaround as the one described by @ampanasiuk with different kernel flags. Added to doc https://github.com/QubesOS/qubes-doc/pull/512

**Comment by fepitre** [comment]
Just a feedback: on a freshly new Acer Predator Helios 300, I encountered the same problem with 'storaged' during the install process with BIOS in Legacy mode. I added 'rd.driver.blacklist=nouveau nouveau.modeset=0 video=vesa:off' to the grub install options and then, everything was fine. @marmarek there is also an integrated graphic card + a GTX1050. I was thinking that maybe we could add such a grub entry just below the already present graphic fallback entry?

**Comment by fepitre** [comment]
There is also another problem which has been solved in the same way: https://groups.google.com/d/msg/qubes-users/aXqX5GGE5EY/A81eni33BAAJ

Any idea why? PCI express related?

**Comment by fepitre** [comment]
@andrewdavidwong  @marmarek : maybe we should open a separate/included issue related to problem with crash during the installer?

**Comment by marmarek** [comment]
First of all, I think `storaged` is unrelated here - it's just a package that happen to be installing at that time. Maybe its installation trigger something (refreshing some hardware state?).
I've seen similar issue on a machine with nvidia + intel GPU, but there it didn't completely frozen but from time to time freeze for ~20s. The freeze there could be triggered by `xrandr -q`. I don't remember details, but AFAIR there were some errors from nouveau (or intel?) driver about PCI access.
Does disabling nvidia in BIOS (if possible) help?

**Comment by fepitre** [comment]
I discussed with friends last week to what could be the problem and you came to the same conclusion, problem probably related to nouveau pci hardware access which could mess up in several pci laptop configurations. From my side, I can't disable NVIDIA in the BIOS and thus I have a big problem with my battery duration (~1 hour only). I tried to install NVIDIA driver (to have some power saving features) without success, using the akmod-nvidia of FC25. Not tried yet the binary from NVIDIA. But, in all cases, there is trouble with such a configuration INTEL+NVIDIA...

**Comment by nystilaps** [comment]
I am trying to install Qubes OS R4.0 on an MSI GS65 8RE notebook.
I encountered two problems: 
1) Installation hangs on storaged installation. I tried different options, mentioned here but it still hangs.
    Options tried: efi=attr=uc modprobe.blacklist=bochs_drm nouveau.blacklist=yes lbm-nouveau.blacklist=yes rd.driver.blacklist=nouveau  nouveau.modeset=0 video=vesa:off acpi=off apm=off irqpoll iommu=no-igfx
2) If I move my SSD to another machine, I can install it there and then move it to the notebook.
    Then it hangs on configuration stage.
I think of removing my WiFi card during installation, but haven't tried it yet.
I would appreciate any help.

**Comment by nystilaps** [comment]
Seems it is normal behaviour:
https://github.com/QubesOS/qubes-issues/issues/1161#issuecomment-156713740

**Comment by akacodeorg** [comment]
Hi All, I’m running into almost the same error installing Qubes-R4.0-x86_64. Install is hanging on “storaged.x86_64 (732/1018)” while installing on:

System76 - Oryx Pro
8 GB GTX 1070
4.1 GHz i7-8750H
32 GB Dual-channel DDR4 at 2400 MHz
512 GB NVMe PCIe M.2 SSD

Will report back if I find workaround.

**Comment by marmarek** [comment]
Are you using USB 3.0 stick as a installation source? I have one (actually bought a bunch of them :/) that cause similar problems, but when connected through USB 2.0 cable or hub, it works.

**Comment by akacodeorg** [comment]
Hi @marmarek, thanks for the heads up. Since your post I have now tried a few different installation methods all with no success. I have tried the following:
-mosDART 16GB USB 3.0 flash drive.
-PNY 8GB USB 2.0 flash drive.
-PNY 64GB USB 3.0 flash drive.
I tried all three methods mentioned above while also plugged into a old USB 2.0 hub.
I have also tried burning iso to DVD and booting from external DVD drive.
I have also downloaded iso again just in case something might have been corrupt.

**Comment by yilmi** [comment]
Hi @akacodeorg, I ran into the same issue on a previous install, however as @marmarek mentioned in a previous comment, the freeze isn't related to the storaged.x86_64 rpm.

You're config is similar to [mine](https://www.qubes-os.org/hcl/#dell-inc_precision-5520_i7-7820hq_kaby-lake_quadro-m1200). At first, I worked around the issue adding `nouveau.modeset=0` kernel parameter and removing `/mapbs` and `/noexitboot`.  

When I wanted to update to Qubes 4.0GA I tried other configurations and used instead `acpi_osi=!` kernel parameter and enabled full iommu in Xen options with `iommu=on`, with this I was able to install and get discrete GPU support.

**Comment by qmontal** [comment]
Hey @yilmi!

Could you get a little bit more on detail about what you did and how you did it? I have the same hardware, and I have not managed to make it work.

On one side, there is no xen.cfg file, this seems to have been deprecated for BOOTX64.cfg file, as it was in version 3.2 but not in 4 (at least the new release available to download, both image and torrent).

Also, the only situation in which I have been able to modify and save successfully the BOOTX64.cfg file is directly inside of the console once Qubes has failed to install, when I can't launch again the installation (when trying to modify directly the files mounting them in another linux machine is not allowing to mount as rw even as sudoer as it is a protected filesystem.

I am pretty lost at this point and don't know to fix it...

Cheers!

Quim

**Comment by yilmi** [comment]
Hi @qmontal,

You're right, it is now the BOOTX64.cfg file that you will have to modify. I added some steps to our documentation some time ago about how to edit it before install, see `Change installer kernel parameters in UEFI` here: https://www.qubes-os.org/doc/uefi-troubleshooting/

For troubleshooting I would use the grub installer as changing parameter can be done at boot time (easier to test different configs). Once I have a it working with Legacy/Grub I test UEFI boot with the same parameters.

The Qubes UEFI installer xen config looks like this (truncated stuff)
```
[global]
default=qubes-verbose

....

[qubes-verbose]
options=console=vga efi=attr=uc
noexitboot=1
mapbs=1
kernel=vmlinuz inst.stage2=hd:LABEL=Qubes-R4.0-x86_64 i915.alpha_support=1
ramdisk=initrd.img

....
```

Make sure that you modify the default boot entry, in this case `qubes-verbose`.

Below the items I had to add/change/remove to get successful install: 
- Add `iommu=on` to the list of `options=`
- add `acpi_osi=!` to the `kernel=` list of parameters
- remove `mapbs=1` and `noexitboot=1`

I also think I had to remove `efi=attr=uc`, try with and without it, if you could confirm afterwards that would be great

**Comment by qmontal** [comment]
Hi @yilmi,

Thanks a lot for your fast reply. I have tried the modified configurations that you mentioned without luck, including acpi_osi=! and acpi_osi=1 (in case the ! was mistaken), both with and without efi=attr=uc; no luck so far, even with legacy boot.

Also tried the nouveau options that @ampanasiuk mentioned previously, same destination. The only thing I know for sure is that there are always errors about:
- ACPI - table/namespace
- nouveau - pointing to table
- Not asking for VNC because we don't have network
- watchdog: BUG: soft lockup - CPU#5 stuck for 23s! [Xorg:1478]
"Installation cannot continue and the system will be rebooted"

I don't think there's much to do here other than keep testing, but doesn't seem to go nowhere :(

Thanks a lot anyway for your clarifications and help :)

**Comment by yilmi** [comment]
@qmontal, I performed the install a few months ago so my memories might not be accurate. You should also try also without adding the `iommu` (add it once the system is installed in your xen.cfg).

I also think at some point I updated my BIOS, not sure if you have the same model as I do, but this might have had an effect.

**Comment by qmontal** [comment]
@yilmi don't worry, you already helped me a lot :D 

My BIOS is also updated to a newer version than the one you tested with, 1.10.1, so this might be making it tougher :)

**Comment by knaku** [comment]
I've struggled with this stupid error for way to long, this is my third time attempting to install qubes or something over a couple of months. Embarrassingly enough I haven't tried it before right now, but so far it seems that turing of internal graphics "fixed it" for me. I have a Clevo laptop with an i6700 with and a gtx 1060. Using just discrete graphics made it possible for it to test the image (2nd option) and also install. This is on legacy, uefi wouldn't load at all before, until  now when I set it to discrete graphics. Will install with uefi, will test if I can get it to work with integrated graphics, I prefer the iGPU battery time over discrete battery time.

**Comment by str4d** [comment]
Same symptom seen (locking up everything except the mouse while installing `storaged`) when installing Qubes 4.0 in Legacy mode (cannot get UEFI working yet) on a Lenovo Thinkpad P1 with a Xeon E-2176M and a NVIDIA P2000. I could not get a non-iso9660 installation USB to boot, so I couldn't try changing EFI options, but I was able to complete installation by switching from hybrid graphics to discrete graphics.

**Comment by loadcorp** [comment]
> Hi All, I’m running into almost the same error installing Qubes-R4.0-x86_64. Install is hanging on “storaged.x86_64 (732/1018)” while installing on:
> 
> System76 - Oryx Pro

Hi, I am using the same laptop (same configuration) and I have the same issue, and when I install Qubes Release 3.2.1 I just adding `nouveau.modeset=0` kernel parameter and removing `/mapbs` and `/noexitboot` - this is worked for me.
But now, when I am trying to install Release 4.0.1 it is not working anymore.

Did you resolve your problem?

**Comment by akacodeorg** [comment]
@loadcorp nope, sorry, I really just gave up, installed Pop_OS and went on with life... Maybe I'll give Qubes another shot after the next major release.

**Comment by loadcorp** [comment]
So, I did it, with help of community. Here is my steps:
https://groups.google.com/d/msg/qubes-users/gssEGXnNhZM/7nllwqbnAwAJ

I think it will helps, if you give one more chance to Qubes OS :)

вс, 3 мар. 2019 г. в 03:51, akaCode <notifications@github.com>:

**Comment by ol7278** [comment]
@loadcorp  - I have a MSI GS65 Stealth Thin 8RE-011, 144Hz FHD, i7-8750H, 16GB DDR4, 256GB NVMe SSD, 6GB GTX 1060  and I've followed your steps described here: 

"This is my steps:

1. I copied .iso-file to linux system.
2. Opened terminal and start command 'sudo su -'
3. 'chmod u+w /path/to/file.iso'
4. 'nano vim /path/to/file.iso'
5. Edit those lines which described in url: https://www.engetsu-consulting.com/blog/installing-qubes-4-0-on-laptops-with-nvidia-gpus-that-do-not-support-the-nouveau-driver
6. Saved file and write on flash drive in DD-mode."

Still get stuck at storaged. I've been tried the qubes 4.0 and 4.0.1 without success. Can you please let me know if you have the same configuration? I've been modified the iso, under linux and under windows as well. I will give another shot today and I will try the legacy mode...Please help.

**Comment by loadcorp** [comment]
> Still get stuck at storaged. I've been tried the qubes 4.0 and 4.0.1 without success. Can you please let me know if you have the same configuration? I've been modified the iso, under linux and under windows as well. I will give another shot today and I will try the legacy mode...Please help.

Actually I modified my iso in Linux via 'vim' editor, saved it, and I copied on Windows system where I installed it via Rufus on my flash drive.

Also you must remember like already mentioned in 5 step: "Note: We can not change the size of the installer ISO or this will cause it to break and not boot". If you see that the size is different after all of your changes then you could not install it.

**Comment by ol7278** [comment]
Thank you for your reply. I actually sort it in windows. It works on 4.0 version only(I've been tried with 4.0.1 either without any luck). I had some issues with the wifi and nvidia drivers, but after updating dom0(testing repos), and sys-net(upgraded to fedora 30), everything works perfect. Still having issues with the external display...but I'm on it. Thank you for everything,  you've been very helpful.

**Comment by loadcorp** [comment]
You are welcome! Actually I had some issues with my sound card/driver (it is the usual problem in Oryx Pro laptop with 4 of Qubes versions). I installed newer version of Kernel in Dom0 and it starts work. On default it was been 4.14.74-1 and I installed 4.19.15-1.

**Comment by ol7278** [comment]
Just followed your example...but I still cannot connect it. When I plug the hdmi , the monitor app pops up, but it shows only the laptop display...I guess I'm still having an issue with the graphic card. I will try to install it from Nvidia directly. I'll come back with an update. Thanks for responding

**Comment by ol7278** [comment]
I had the same issue. Switch to legacy, choose the second option(Troubleshoot one), pres tab, remove rgbh and add rd.driver.blacklist=nouveau nouveau.modeset=0. Hit enter, escape to quit sacnning the image and follow the instructions. It works perfectly now.

**Comment by loadcorp** [comment]
Strange that the problem hasn't been fixed yet. Although now version 4.0.3.

**I Copy-Pasted this quote from here which describe fully about this problem on my Laptop:**
https://www.engetsu-consulting.com/blog/installing-qubes-4-0-on-laptops-with-nvidia-gpus-that-do-not-support-the-nouveau-driver

_"To install Qubes OS 4.0 on laptops with integrated Intel and Nvidia GPUs that do not support the nouveau driver we need to binary edit the installer ISO. By default the installer will try to use the nouveau driver and will be unable to enter the setup until we change the kernel boot parameters.

Note: we can not tab to enter the kernel boot parameters with the Qubes OS 4.0 installer ISO."_


Today I installed again this version and unfortunately still had the same problem.

**At this time I repeat all steps in Windows:**
1. Install 'gvim' - https://github.com/vim/vim-win32-installer/releases
2. Download plugins for 'gvim' - https://github.com/mbbill/fencview
3. Change .ISO file via 'gvim'
4. Write the ISO via 'Rufus' in DD mode - https://rufus.ie/

**Comment by ol7278** [comment]
@loadcorp - go to https://ftp.qubes-os.org and download the  R4.0.2-RC1 iso. I have no explanation but it works with low resolution. (I believe it wrongly takes a radeon gpu driver). I'm using an rtx2080. After a successful installation, just update the kernel to the kernel latest from current testing repo: $sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing kernel-latest
It works perfectly for me. I hope it helps

**Comment by ol7278** [comment]
The issue will not be solved until a kernel 5.6+ will come as a default. It does not work on 4.1 alpha versions neither.

**Comment by Simbaclaws** [comment]
@ol7278 Your solution doesn't work for me by trying R4.0.2-RC1 and updating to the latest kernel.
I can not seem to get past the storaged software package like mentioned earlier. And it does not jump to a low resolution.
I'm on a oryx pro 4 from system76.

Is there no way for me to get qubes os working till a later kernel will be shipped?

**Comment by DemiMarie** [comment]
@marmarek can we ship more than one kernel in the default ISO, and let the user select which to use at boot time?  Ideally, we would do this for both R4.0 and R4.1.

**Comment by marmarek** [comment]
Yes, AFAIR we had similar thing before, @fepitre look for "extrakernels".
One slight issue is that we test "latest" much less (for example it isn't plugged into openQA), but I think we can change that.

**Comment by DemiMarie** [comment]
> > @marmarek can we ship more than one kernel in the default ISO, and let the user select which to use at boot time? Ideally, we would do this for both R4.0 and R4.1.
> 
> This is possible. By multiple you mean LTS + latest one right?

Correct.

**Comment by Simbaclaws** [comment]
I got it installed eventually by following this part:

> @loadcorp - I have a MSI GS65 Stealth Thin 8RE-011, 144Hz FHD, i7-8750H, 16GB DDR4, 256GB NVMe SSD, 6GB GTX 1060 and I've followed your steps described here:
> 
> "This is my steps:
> 
>     1. I copied .iso-file to linux system.
> 
>     2. Opened terminal and start command 'sudo su -'
> 
>     3. 'chmod u+w /path/to/file.iso'
> 
>     4. 'nano vim /path/to/file.iso'
> 
>     5. Edit those lines which described in url: https://www.engetsu-consulting.com/blog/installing-qubes-4-0-on-laptops-with-nvidia-gpus-that-do-not-support-the-nouveau-driver
> 
>     6. Saved file and write on flash drive in DD-mode."
> 
> 
> Still get stuck at storaged. I've been tried the qubes 4.0 and 4.0.1 without success. Can you please let me know if you have the same configuration? I've been modified the iso, under linux and under windows as well. I will give another shot today and I will try the legacy mode...Please help.

But if the latest kernel can fix these issues and it can be shipped as either a second option or as one of the versions. That might help too.

**Comment by ol7278** [comment]
@Simbaclaws That will be nice
