### ISSUE TITLE
Archlinux template Qubes 4.0 cannot satisfy dependencies

### ISSUE THREAD

**Issue by fosslinux** [QubesOS/qubes-issues#3908]
### Qubes OS version:
R4.0

### Affected component(s): 
The Archlinux template build in Qubes 4.0.
---
### Steps to reproduce the behavior:
Exactly same instructions as #3185:
Try to build the archlinux template:

1. Install and set up the needed prerequisites for building QubesOS
2. Clone `qubes-builder`
3. Copy `example-configs/qubes-os-master.conf` as `builder.conf`
4. Set `DISTS_VM` to `archlinux` and add `builder-archlinux` to `COMPONENTS` and `BUILDER_PLUGINS`
5. Run `make get-sources`, `make qubes-vm`, `make template`

### Expected behavior:
The template should successfully build.

### Actual behavior:
At the end of `make template`, I get this error:

```
  --> Finishing installation of qubes packages...
resolving dependencies...
warning: cannot resolve "xorg-server<1.20.0", a dependency of "qubes-vm-gui"
:: The following package cannot be upgraded due to unresolvable dependencies:
      qubes-vm-gui

:: Do you want to skip the above package for this upgrade? [y/N] error: failed to prepare transaction (could not satisfy dependencies)

:: qubes-vm-gui: requires xorg-server<1.20.0
make[1]: *** [Makefile:59: rootimg-build] Error 1
```

### General notes:
This stems from #3185. There have been some (slightly) similar issues in the past related, but the solutions don't work/don't work on Qubes R4.0.

What I can make from the error is that `qubes-vm-gui` requires `xorg-server` under version `1.20.0`. The current version on Archlinux repositories is `1.20.0-2`. Should the PKGBUILD be edited so it works, or just can't we have this? If `1.20.0` is impossible, how can I get around this error?

---
### Related issues:
#3185

**Comment by sstt011** [comment]
cc @na-- @andrewdavidwong @mannp
Any thoughts?

**Comment by sstt011** [comment]
Related: #2585

**Comment by marmarek** [comment]
Pull requests fixing this:
https://github.com/QubesOS/qubes-gui-agent-linux/pull/41
https://github.com/QubesOS/qubes-gui-agent-linux/pull/40

**Comment by sstt011** [comment]
Fixed with https://github.com/QubesOS/qubes-gui-agent-linux/pull/42.

**Comment by dadigi** [comment]
arch now updates to xorg-server 1.20.4-1 which breaks again the dependency in qubes-gui-agent-linux/archlinux/PKGBUILD

**Comment by zaoqi** [comment]
now archlinux template can build without errors

**Comment by ejose19** [comment]
Error is happening again with xorg-server (1.20.6-1)

**Comment by ejose19** [comment]
@marmarek 
I've installed latest qubes-gui-agent-linux (running pacman -Q qubes-vm-gui returns 4.0.27-9) yet I still get the dependency issue when doing pacman -Syu (:: installing xorg-server (1.20.6-1) breaks dependency 'xorg-server<1.20.6' required by qubes-vm-gui) any ideas what I could be missing?

**Comment by ejose19** [comment]
I see the latest version on https://github.com/QubesOS/qubes-gui-agent-linux is 4.1.5 yet when following the steps from https://www.qubes-os.org/doc/building-archlinux-template/ I get a pkg with 4.0.27. Can you guide me where is a tutorial so I can build latest qubes-vm-gui using only its corresponding repository?

**Comment by marmarek** [comment]
> I've installed latest qubes-gui-agent-linux (running pacman -Q qubes-vm-gui returns 4.0.27-9) yet I still get the dependency issue when doing pacman -Syu (:: installing xorg-server (1.20.6-1) breaks dependency 'xorg-server<1.20.6' required by qubes-vm-gui) any ideas what I could be missing?

Again the xorg-server was updated in Archlinux, and qubes-gui-agent-linux needs to be checked if it's compatible with the new version (there is input and video xorg driver). It would be much better, if qubes-gui-agent-linux would depend on on a specific xorg-server package version, but on ABI version (like we do for every other distribution). I see xorg-server [provides](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/xorg-server#n116) it. Anyone knowing Arch packaging can confirm it can be used in a normal dependency?



>  see the latest version on https://github.com/QubesOS/qubes-gui-agent-linux is 4.1.5 yet when following the steps from https://www.qubes-os.org/doc/building-archlinux-template/ I get a pkg with 4.0.27

You should look at `release4.0` branch for R4.0. 4.1.x packages are for Qubes R4.1 (in development).

**Comment by ejose19** [comment]
@marmarek Thanks for pointing me that, I applied https://github.com/QubesOS/qubes-gui-agent-linux/pull/79 manually to branch 4.0 (since it's the one that uses qubes-builder but that branch doesn't have the patch) and now could install qubes-vm-gui without giving dependency issues.

**Comment by zaoqi** [comment]
I get this error:
```
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> pulseaudio
  -> xorg-server-devel
  -> xorg-util-macros
  -> libxcomposite
  -> libxt
  -> qubes-vm-gui-common
==> ERROR: Could not resolve all dependencies.
make[2]: *** [/home/user/qubes-builder/qubes-src/builder-archlinux/Makefile.archlinux:121: dist-package] Error 8
make[1]: *** [Makefile.generic:180: packages] Error 1
make: *** [Makefile:226: gui-agent-linux-vm] Error 1
```

**Comment by ejose19** [comment]
@zaoqi can you give context on which step you got that error?

**Comment by zaoqi** [comment]
@ejose19 
```
$ make install-deps && make get-sources && make qubes-vm && make template
```

**Comment by ptitdoc** [comment]
Hello @marmarek. I followed your proposal from last year (sorry for getting there only now) to update archlinux package based on ABI version instead of xorg-server version.
I'm not sure however if we need to check all the ABI versions for XEXTENSION, XINPUT and XVIDEO. I put all of them as dependency in the commit above.

**Comment by andrewdavidwong** [comment]
> I get this error:
> 
> ```
> error: failed to commit transaction (unexpected error)
> Errors occurred, no packages were upgraded.
> ==> ERROR: 'pacman' failed to install missing dependencies.
> ==> Missing dependencies:
>   -> pulseaudio
>   -> xorg-server-devel
>   -> xorg-util-macros
>   -> libxcomposite
>   -> libxt
>   -> qubes-vm-gui-common
> ==> ERROR: Could not resolve all dependencies.
> make[2]: *** [/home/user/qubes-builder/qubes-src/builder-archlinux/Makefile.archlinux:121: dist-package] Error 8
> make[1]: *** [Makefile.generic:180: packages] Error 1
> make: *** [Makefile:226: gui-agent-linux-vm] Error 1
> ```

This looks like #4436.

**Comment by Qiyamah** [comment]
I am getting another failure:
`qubes/qubes-vm-networking 4.0.58-15
    Qubes OS tools allowing to use a Qubes VM as a NetVM/ProxyVM
qubes/qubes-vm-pulseaudio 4.0.31-10
    Pulseaudio support for Qubes VM
qubes/qubes-vm-utils 4.0.31-10
    Common Linux files for Qubes VM.
qubes/qubes-vm-xen 4.8.5-26
    Xen is a virtual machine monitor
  --> Installing mandatory qubes packages...
error: target not found: qubes-vm-dependencies
make[1]: *** [Makefile:66: rootimg-build] Error 1
`
It still needs fixing.

**Comment by icequbes1** [comment]
@Qiyamah This issue is due to the work in R4.1 that hasn't yet been backported to R4.0.

ref: https://github.com/QubesOS/qubes-meta-packages/pull/27

**Comment by unman** [comment]
@andrewdavidwong  @fosslinux  
As a result of changes merged and updated packages, the Arch template for 4.0 builds correctly with no dependency errors.
Please close this issue.
