### ISSUE TITLE
qubes-vm-pulseaudio dependency failed with new pulseaudio-14.0-1

### ISSUE THREAD

**Issue by lubellier** [QubesOS/qubes-issues#6234]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
functionality: ArchLinux TemplateVM update
component: qubes-vm-pulseaudio

**Brief summary**
On Archlinux templateVM OS update, I got an package dependency error related to pulseaudio

**How Reproducible**
From Qube Manager, update the Archlinux Template VM

**To Reproduce**
1. Open Qube Manager
2. Right click on archlinux templateVM and choose Update qube

**Expected behavior**
OS update

**Actual behavior**
In the Details area of Qubes Updater, got the below error
```
error: failed to prepare transaction (could not satisfy dependencies)
installing pulseaudio (14.0-1) breaks dependency 'pulseaudio<14.0' required by qubes-vm-pulseaudio
```
**Screenshots**
N/A

**Additional context**
Previous updates worked, this issue comes with the archlinux pulseaudio update from 13.99.3+4+gd83ad6990-1 to 14.0.1

Archlinux template installed with [building-archlinux-template](https://www.qubes-os.org/doc/building-archlinux-template/).

**Solutions you've tried**
The manual update with `sudo pacman -Syu` failed with the same error.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
related to https://github.com/QubesOS/qubes-issues/issues/6172 ?

**Comment by lubellier** [comment]
label:"C: Arch Linux"

**Comment by icequbes1** [comment]
FWIW you can symlink 14.0 to 13.99.3 headers and modify the dependency to be `<14.1`. A test build with this workaround worked in terms of "I hear something when playing a youtube video". You can also just 

I'm not sure how the Qubes OS team wants to handle this though...are we going to have open a new issue every time Arch updates PulseAudio?

**Comment by waycloak** [comment]
Hi, this also occurs for me on Fedora 32 template

```
[user@fedora-32 ~]$ sudo dnf update
Dependencies resolved.

 Problem 1: package pulseaudio-qubes-4.0.31-1.fc32.x86_64 requires pulseaudio = 13.99.1, but none of the providers can be installed
  - cannot install both pulseaudio-14.0-1.fc32.x86_64 and pulseaudio-13.99.1-4.fc32.x86_64
  - cannot install both pulseaudio-13.99.1-3.fc32.x86_64 and pulseaudio-14.0-1.fc32.x86_64
  - cannot install the best update candidate for package pulseaudio-qubes-4.0.31-1.fc32.x86_64
  - cannot install the best update candidate for package pulseaudio-13.99.1-4.fc32.x86_64
 Problem 2: problem with installed package pulseaudio-qubes-4.0.31-1.fc32.x86_64
  - package pulseaudio-qubes-4.0.31-1.fc32.x86_64 requires pulseaudio = 13.99.1, but none of the providers can be installed
  - package pulseaudio-13.99.1-4.fc32.x86_64 requires pulseaudio-libs(x86-64) = 13.99.1-4.fc32, but none of the providers can be installed
  - package pulseaudio-13.99.1-3.fc32.x86_64 requires pulseaudio-libs(x86-64) = 13.99.1-3.fc32, but none of the providers can be installed
  - cannot install both pulseaudio-libs-14.0-1.fc32.x86_64 and pulseaudio-libs-13.99.1-4.fc32.x86_64
  - cannot install both pulseaudio-libs-13.99.1-3.fc32.x86_64 and pulseaudio-libs-14.0-1.fc32.x86_64
  - cannot install the best update candidate for package pulseaudio-libs-13.99.1-4.fc32.x86_64
 Problem 3: package qubes-vm-recommended-4.0.7-1.fc32.noarch requires pulseaudio-qubes, but none of the providers can be installed
  - package pulseaudio-qubes-4.0.31-1.fc32.x86_64 requires pulseaudio = 13.99.1, but none of the providers can be installed
  - package pulseaudio-qubes-4.0.29-1.fc32.x86_64 requires pulseaudio = 13.99.1, but none of the providers can be installed
  - package pulseaudio-qubes-4.0.30-1.fc32.x86_64 requires pulseaudio = 13.99.1, but none of the providers can be installed
  - cannot install both pulseaudio-14.0-1.fc32.x86_64 and pulseaudio-13.99.1-4.fc32.x86_64
  - cannot install both pulseaudio-13.99.1-3.fc32.x86_64 and pulseaudio-14.0-1.fc32.x86_64
  - package pulseaudio-module-bluetooth-14.0-1.fc32.x86_64 requires libpulsecore-14.0.so()(64bit), but none of the providers can be installed
  - package pulseaudio-module-bluetooth-14.0-1.fc32.x86_64 requires pulseaudio(x86-64) = 14.0-1.fc32, but none of the providers can be installed
  - cannot install the best update candidate for package qubes-vm-recommended-4.0.7-1.fc32.noarch
  - cannot install the best update candidate for package pulseaudio-module-bluetooth-13.99.1-4.fc32.x86_64
 Problem 4: problem with installed package qubes-vm-recommended-4.0.7-1.fc32.noarch
  - package qubes-vm-recommended-4.0.7-1.fc32.noarch requires pulseaudio-qubes, but none of the providers can be installed
  - package pulseaudio-qubes-4.0.31-1.fc32.x86_64 requires pulseaudio = 13.99.1, but none of the providers can be installed
  - package pulseaudio-qubes-4.0.29-1.fc32.x86_64 requires pulseaudio = 13.99.1, but none of the providers can be installed
  - package pulseaudio-qubes-4.0.30-1.fc32.x86_64 requires pulseaudio = 13.99.1, but none of the providers can be installed
  - cannot install both pulseaudio-14.0-1.fc32.x86_64 and pulseaudio-13.99.1-4.fc32.x86_64
  - cannot install both pulseaudio-13.99.1-3.fc32.x86_64 and pulseaudio-14.0-1.fc32.x86_64
  - package pulseaudio-module-x11-14.0-1.fc32.x86_64 requires libpulsecore-14.0.so()(64bit), but none of the providers can be installed
  - package pulseaudio-module-x11-14.0-1.fc32.x86_64 requires pulseaudio(x86-64) = 14.0-1.fc32, but none of the providers can be installed
  - cannot install the best update candidate for package pulseaudio-module-x11-13.99.1-4.fc32.x86_64

```

**Comment by kalkin** [comment]
Since a few days building the iso fails, because of this.

FIX: I applied the patch and also fixed a few version requirements in `*.spec.in` files.

**Comment by tsteinholz** [comment]
Same issue, I fixed it with `ln -s qubes-src/gui-agent-linux/pulse/pulsecore-13.2 qubes-src/gui-agent-linux/pulse/pulsecore-14.0`.

**Comment by lubellier** [comment]
> To test this update, please install it with the following command:

I validated on Fedora, got sound :-)

> ```
> sudo yum update --enablerepo=qubes-vm-r4.0-current-testing
> ```

The bot should be updated : replace `yum` by `dnf`

**Comment by lubellier** [comment]
> The package `qubes-gui-agent_4.0.32-1` has been pushed to the `r4.0` testing repository for the Debian template.

I validated on Debian, got sound also :-)

**Comment by evadogstar** [comment]
I also fall into the same story. If somebody like I used `--allowerasing` flag when you see this error message then to fix it after `sudo dnf update --enablerepo=qubes-vm-r4.0-current-testing` you should install `sudo dnf install pulseaudio-qubes` package.

**Comment by tlaurion** [comment]
`[user@fedora-32 ~]$ sudo dnf update -y --enablerepo=qubes-vm-r4.0-current-testing pulseaudio*`

Fixed it for Fedora-32. No problem over debian-10.

**Comment by lubellier** [comment]
I tested the r4.0-buster-stable and r4.0-fc32-stable versions, the VM updates worked and the sound works well, thanks a lot  :+1: .
Is the Archlinux update also scheduled ? Initially I reported this issue for the Archlinux templateVM.

**Comment by RooneyMcNibNug** [comment]
Can confirm the `pulseaudio` packages in question install and work on Fedora 32 Template after a quick `dnf update` just now - thank you for this fix.

**Comment by andrewdavidwong** [comment]
Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by lubellier** [comment]
Hi @andrewdavidwong ,
the issue still exists for ArchLinux. I didn't see available update packages for this OS.
Initially I reported this issue for the ArchLinux templateVM.
The error message:
```
$ sudo pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing pulseaudio (14.0-1) breaks dependency 'pulseaudio<14.0' required by qubes-vm-pulseaudio
```

Thank you.

**Comment by andrewdavidwong** [comment]
> Hi @andrewdavidwong ,
> the issue still exists for ArchLinux. I didn't see available update packages for this OS.
> Initially I reported this issue for the ArchLinux templateVM.
> The error message:
> 
> ```
> $ sudo pacman -Syu
> :: Synchronizing package databases...
>  core is up to date
>  extra is up to date
>  community is up to date
>  multilib is up to date
> :: Starting full system upgrade...
> resolving dependencies...
> looking for conflicting packages...
> error: failed to prepare transaction (could not satisfy dependencies)
> :: installing pulseaudio (14.0-1) breaks dependency 'pulseaudio<14.0' required by qubes-vm-pulseaudio
> ```
> 
> Thank you.

FYI @fepitre

**Comment by icequbes1** [comment]
This issue was resolved 2020-12-02 with version 4.0.32 of gui-agent-linux, one month ago.

It appears the issue is kept open as the package is not available via `pacman -Syu`?

We (Arch users) must manually build using qubes-builder for updates to qubes-* packages.

**Comment by lubellier** [comment]
> We (Arch users) must manually build using qubes-builder for updates to qubes-* packages.

Thanks @icequbes1 for this information. 

It appears I miss-understood the ArchLinux update process for qubes-* packages, so now I'll follow the process. I'm a long time ArchLinux user, but only since 6 months for ArchLinux over Qubes OS.

Should I build a new ArchLinux templateVM rpm or only create my [own ArchLinux repository](https://github.com/Qubes-Community/Contents/blob/master/docs/building/building-archlinux-template.md#creating-a-archlinux-repository) ?

**Comment by lubellier** [comment]
@icequbes1 : I built my own ArchLinux repository, and as expected it works and gets sound, thanks for your comment.

@andrewdavidwong : This ticket is closable, ArchLinux users must build themself the qubes-* packages (see the above @icequbes1's comment)

**Comment by andrewdavidwong** [comment]
Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by icequbes1** [comment]
>>
>> We (Arch users) must manually build using qubes-builder for updates to qubes-* packages.
>>
>>
>
> Thanks > @icequbes1 <https://github.com/icequbes1>>  for this information.
>
>
> It appears I miss-understood the ArchLinux update process for qubes-* packages, so now I'll follow the process. I'm a long time ArchLinux user, but only since 6 months for ArchLinux over Qubes OS.
>
>
> Should I build a new ArchLinux templateVM rpm or only create my > own ArchLinux repository <https://github.com/Qubes-Community/Contents/blob/master/docs/building/building-archlinux-template.md#creating-a-archlinux-repository>>  ?
>
>

Note that my comments are only as a Qubes OS user with no knowledge of internal decisions, but as I understand, the Qubes team has setup infrastructure to build, sign and host Qubes packages for Arch (archlinux.qubes-os.org, see qubes-meta-packages repo), but it's not fully integrated yet within a vanilla template build.

You can sneak a look and see the fixed package for this issue _is_ on the archlinux repo under current-testing (qubes-vm-gui-4.0.32-10-x86_64.pkg.tar.zst)...but....

There has been activity in qubes-builder-archlinux that would affect the template base before packages are installed. Because of that, it's safer to rebuild the template until the infrastructure is securely integrated/tested. Otherwise it would not serve the purpose if hosted packages cannot be trusted to come from Qubes team.


-- 
PGP Key: 871370CDA06BBA0BAB7E8C168CDFE284B142D0EA
