### ISSUE TITLE
Updater keeps advertising 'empty' updates

### ISSUE THREAD

**Issue by Ark-of-the-copepod** [QubesOS/qubes-issues#7220]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

The updater keeps prompting to update Fedora 34, even in absence of real updates. Several days and restarts.

### Steps to reproduce

1. Start system
2. Update through updater
3. Observer no updates made OR some real updates are made
(4. Optional: restart)
5. Follow Updater prompt
6. No updates

### Expected behavior

Update or die.

### Actual behavior

Continual prompt for updates. 

Details output:
```
Updating fedora-34

fedora-34:
  ----------
            ID: dnf-and-rpm
      Function: pkg.installed
        Result: True
       Comment: All specified packages are already installed and are at the desired version
       Started: 20:55:34.587530
      Duration: 1403.244 ms
       Changes:   
  ----------
            ID: /usr/lib/rpm/macros.d/macros.qubes
      Function: file.absent
        Result: True
       Comment: File /usr/lib/rpm/macros.d/macros.qubes is not present
       Started: 20:55:35.997654
      Duration: 1.267 ms
       Changes:   
  ----------
            ID: dnf-makecache
      Function: cmd.script
        Result: True
       Comment: DNF cache successfully created
       Started: 20:55:36.001465
      Duration: 13363.438 ms
       Changes:   
  ----------
            ID: Disable deltarpm
      Function: file.append
          Name: /etc/dnf/dnf.conf
        Result: True
       Comment: File /etc/dnf/dnf.conf is in correct state
       Started: 20:55:49.365210
      Duration: 3.76 ms
       Changes:   
  ----------
            ID: update
      Function: pkg.uptodate
        Result: True
       Comment: Upgrade ran successfully
       Started: 20:55:49.369908
      Duration: 29453.63 ms
       Changes:   
  ----------
            ID: notify-updates
      Function: cmd.run
          Name: /usr/lib/qubes/upgrades-status-notify
        Result: True
       Comment: Command "/usr/lib/qubes/upgrades-status-notify" run
       Started: 20:56:18.823886
      Duration: 3827.782 ms
       Changes:   
                ----------
                pid:
                    1168
                retcode:
                    0
                stderr:
                stdout:
  
  Summary for fedora-34
  ------------
  Succeeded: 6 (changed=1)
  Failed:    0
  ------------
  Total states run:     6
  Total run time:  48.053 s
```

**Comment by andrewdavidwong** [comment]
Sounds like a certain recurring problem that has been around for years and that was thought to have been fixed, but I can no longer find the old issue for it.

**Comment by DemiMarie** [comment]
@Ark-of-the-copepod what happens if you run `dnf` manually in the template?

**Comment by Ark-of-the-copepod** [comment]
Is that diagnostic or a work-around? I have read advice @andrewdavidwong that Salt needs to do work so do it in Updater. (I haven't educated myself about Salt yet so this isn't a criticism of that advice, just trying to understand.)

Anyway, this may be my own fault: missing package dependencies on a browser I installed. But I don't understand why installing the dependencies doesn't solve the problem.

```
[user@fedora-34 ~]$ sudo dnf upgrade
Last metadata expiration check: 0:03:17 ago on Sat Jan 22 19:19:26 2022.
Dependencies resolved.

 Problem: cannot install the best update candidate for package librewolf-96.0.1-1.fc34.x86_64
  - nothing provides libc.so.6(GLIBC_2.34)(64bit) needed by librewolf-96.0.1-1.fc35.x86_64
================================================================================
 Package         Architecture Version             Repository               Size
================================================================================
Skipping packages with broken dependencies:
 librewolf       x86_64       96.0.1-1.fc35       rpm.librewolf.net        56 M

Transaction Summary
================================================================================
Skip  1 Package

Nothing to do.
Complete!
[user@fedora-34 ~]$ sudo apt install libc.so.6
sudo: apt: command not found
[user@fedora-34 ~]$ sudo dnf install libc.so.6
Last metadata expiration check: 0:03:57 ago on Sat Jan 22 19:19:26 2022.
Dependencies resolved.
================================================================================
 Package         Architecture  Version                   Repository        Size
================================================================================
Installing:
 glibc           i686          2.33-20.fc34              updates          3.3 M
Installing dependencies:
 libgcc          i686          11.2.1-1.fc34             updates          116 k

Transaction Summary
================================================================================
Install  2 Packages

Total download size: 3.5 M
Installed size: 13 M
Is this ok [y/N]: y
Downloading Packages:
(1/2): libgcc-11.2.1-1.fc34.i686.rpm            143 kB/s | 116 kB     00:00    
(2/2): glibc-2.33-20.fc34.i686.rpm              1.6 MB/s | 3.3 MB     00:02    
--------------------------------------------------------------------------------
Total                                           916 kB/s | 3.5 MB     00:03     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Installing       : libgcc-11.2.1-1.fc34.i686                              1/2 
  Running scriptlet: libgcc-11.2.1-1.fc34.i686                              1/2 
  Running scriptlet: glibc-2.33-20.fc34.i686                                2/2 
  Installing       : glibc-2.33-20.fc34.i686                                2/2 
  Running scriptlet: glibc-2.33-20.fc34.i686                                2/2 
  Verifying        : glibc-2.33-20.fc34.i686                                1/2 
  Verifying        : libgcc-11.2.1-1.fc34.i686                              2/2 
Notifying dom0 about installed applications

Installed:
  glibc-2.33-20.fc34.i686               libgcc-11.2.1-1.fc34.i686              

Complete!
[user@fedora-34 ~]$ sudo dnf upgrade
Last metadata expiration check: 0:04:49 ago on Sat Jan 22 19:19:26 2022.
Dependencies resolved.

 Problem: cannot install the best update candidate for package librewolf-96.0.1-1.fc34.x86_64
  - nothing provides libc.so.6(GLIBC_2.34)(64bit) needed by librewolf-96.0.1-1.fc35.x86_64
================================================================================
 Package         Architecture Version             Repository               Size
================================================================================
Skipping packages with broken dependencies:
 librewolf       x86_64       96.0.1-1.fc35       rpm.librewolf.net        56 M

Transaction Summary
================================================================================
Skip  1 Package

Nothing to do.
Complete!
```

Running Updater again after the above - no change in behavior. Its not letting me copy the message, for some reason. I will restart the machine and try again.

**Comment by unman** [comment]
Perhaps one of #6276, #4667, #4650 may relate

**Comment by Ark-of-the-copepod** [comment]
Restarted, still there.
Removed `librewolf`, problem solved.

I had to install [a repository](https://librewolf.net/installation/fedora/) for this app. (It felt safe: Its a largeish, visible project, the signature is from an email that is included on the project GitLab page).

Installing the package, I ran into a hiccup that mentioned `broken dependencies` - but it installed the previous package, and worked just fine. I just figured that was ok - an automatic process that fixed it. (I'm not sure of that right now).

For example, trying again:
```
[user@fedora-34 ~]$ sudo dnf install librewolf
Last metadata expiration check: 0:42:06 ago on Sat Jan 22 19:34:15 2022.
Dependencies resolved.

 Problem: cannot install the best candidate for the job
  - nothing provides libc.so.6(GLIBC_2.34)(64bit) needed by librewolf-96.0.2-1.fc35.x86_64
================================================================================
 Package         Architecture Version             Repository               Size
================================================================================
Installing:
 librewolf       x86_64       96.0.2-1.fc34       rpm.librewolf.net        56 M
Skipping packages with broken dependencies:
 librewolf       x86_64       96.0.2-1.fc35       rpm.librewolf.net        56 M

Transaction Summary
================================================================================
Install  1 Package
Skip     1 Package

Total download size: 56 M
Installed size: 209 M
Is this ok [y/N]: n
Operation aborted.
```

I don't understand the magnitude of the mistake I might have made in the installation of this (if an older version was badly risky for a user, why would it still be in the standard repo? Are there no safeguards?). But its in _my_ Fedora template, and its really my responsibility. 

I should have put the two things together, (doing the installation, observing Updater malfunction), but I think that happened over a couple of days. Fedora updates so frequently that it could 'mask' the problem. Makes attribution difficult.

On the other hand, there is nothing in the Updater message to indicate that there's any problem anywhere (and this has been a problem before, as @andrewdavidwong points out). One shrugs one's shoulders and pushes on - Qubes has idiosyncracies.

Since we are advised _not_ to update via the template command line, I've stayed away from it until asked.

For a user at my level, I feel there needs to be better notification from Updater.

**Comment by andrewdavidwong** [comment]
Duplicate of #6279.

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
