### ISSUE TITLE
Firefox window content freezes randomly

### ISSUE THREAD

**Issue by Warthog-Capital** [QubesOS/qubes-issues#7695]
### Qubes OS release

4.1.1

### Brief summary

While using Firefox on the Fedora 35 and 36 XFCE templates, sometimes the window content freezes. However, the window _title_ still changes when clicking on different tabs, and when switching between windows, the window content is updated as well. Closing and opening Firefox again solves the problem for the moment.

### Steps to reproduce

1. Open Firefox
2. Surf the web, scrolling, clicking and sometimes selecting text with the mouse pointer
3. Wait for Firefox to freeze.

### Expected behavior

The window content should update immediately, while interacting with the application.

### Actual behavior

The window content is only updated after switching to a different window (Alt-Tab), and then switching back to Firefox. This way it is impossible to fluently interact with the application.

Example:
1. Click on an existing open tab. The window title changes to the title of that tab's website, but otherwise nothing happens
2. Hit Alt-Tab twice
3. Firefox now shows the open tab, but it is still not possible to interact with the site

### Solutions I have tried

Closing Firefox and opening it again solves the problem, until it freezes the next time.

**Comment by resulin** [comment]
I experience the same bug from time to time, but it's hard to find a way to reliably reproduce it.

**Comment by DemiMarie** [comment]
@SchnWalter I recommend copying the files to a disposable VM first

**Comment by marmarek** [comment]
I observe this from time to time too. I captured gui-agent debug log this time. I'm not sure if any of this give any hits, for me it looks rather normal. I do _not_ see any process killed by oom-killer. I'm not exactly sure what action caused the freeze, but I found it frozen when I switched back to it, after doing something on another workspace (in another VM).

<details>

0x100002b is Firefox
0x200002 is qubes-gui's 1x1 window

```
(before freeze)
Aug 26 00:21:38 disp9221 qubes-gui[550]: received message type 128 for 0x100002b
Aug 26 00:21:38 disp9221 qubes-gui[550]: 0x100002b lost focus
Aug 26 00:21:38 disp9221 qubes-gui[550]: received message type 127 for 0x100002b
(after this point it was frozen)
Aug 26 00:23:43 disp9221 qubes-gui[550]: Skipping unmanaged window 0x200002received message type 142 for 0x0
Aug 26 00:23:43 disp9221 qubes-gui[550]: received message type 127 for 0x100002b
Aug 26 00:23:43 disp9221 qubes-gui[550]: Skipping unmanaged window 0x200002received message type 142 for 0x0
Aug 26 00:23:43 disp9221 qubes-gui[550]: received message type 128 for 0x100002b
Aug 26 00:23:43 disp9221 qubes-gui[550]: WM_TAKE_FOCUS sent for 0x100002b
Aug 26 00:23:43 disp9221 qubes-gui[550]: 0x100002b raised
Aug 26 00:23:43 disp9221 qubes-gui[550]: handle configure event 0x100002b w=1280 h=1040 ovr=0
Aug 26 00:23:43 disp9221 qubes-gui[550]: handle property WM_HINTS for window 0x100002b
Aug 26 00:23:43 disp9221 qubes-gui[550]: Received input hint 0x1 for Window 0x100002b
Aug 26 00:23:43 disp9221 qubes-gui[550]: received message type 124 for 0x100002b
Aug 26 00:23:43 disp9221 qubes-gui[550]: received message type 126 for 0x100002b
Aug 26 00:23:43 disp9221 qubes-gui[550]: received message type 126 for 0x100002b
Aug 26 00:23:43 disp9221 qubes-gui[550]: received message type 126 for 0x100002b
```

**Comment by brendanhoar** [comment]
I've been meaning to try to debug this in Firefox or tor browser as I've seen it happen in both. One area I haven't explored is looking at the resource limits/used stats in /sys (/proc?) to see if it gets triggered by hitting hard limits (probably not) or soft limits that might temporarily be hit and then lag before being increased by firefox/tor browser.

B

**Comment by DemiMarie** [comment]
@marmarek what is your dmesg?  Are block devices still working?

**Comment by marmarek** [comment]
> @marmarek what is your dmesg? 

Nothing else. The above log is all I have in journal at this time.

> Are block devices still working?

Yes. All the other windows are functional too. It's only this Firefox instance that is frozen. Firefox works correctly after restarting it (for some time). This bug made me starting xterm in DispVM and starting Firefox from there (so I can restart it and load previous session from history), instead of starting Firefox in DispVM directly (where restarting would kill DispVM).

**Comment by marmarek** [comment]
I've been running some Firefox instances via `x11trace` for the past week+ and the issue did not reproduced there. At the same time, I did hit the issue few times in another VM with the same Firefox version (but without x11trace there). It could be just coincidence (the issue doesn't happen that often), but it could be also some side effect of `x11trace` (increased latency reduce chance of some race condition?).

**Comment by Warthog-Capital** [comment]
FWIW I have a habit of randomly selecting text with the mouse while reading. I have the impression that this issue happens most often while I am doing that kind of movement. This could be coincidental of course. I wonder if anybody else here observes a similar correlation?

Specificially, what I am doing is:

- With a physical mouse: Hold the left mouse button and move the mouse pointer up and down, causing text to be selected and unselected in quick succession as I go up and down.
- With a touchpad: Double-tap, and while on the second tap, keep the finger on the touchpad and move the mouse pointer up and down.

**Comment by vladimir-lu** [comment]
This seems to happen outside of firefox with almost all other applications as well (fedora-36). I will edit this comment to confirm whether I see the fd#4 related issues in straces.

**Comment by gangamstyle** [comment]
Debugging something (window manager? xen? video driver?) in dom0 can help too, because dom0 receives "image" from VM and this can be related to broken dom0<->VM communication, sorry I don't know how this works internally.

**Comment by resulin** [comment]
Happens quiet often now with Tor Browser 12.0 (based on Firefox 102 ESR).

**Comment by resulin** [comment]
@na-- I always had `Use recommended performance settings` checked when encountering this problem.

**Comment by marmarek** [comment]
I also didn't got this issue in recent week or two, but got it semi-frequently before. I'd wait a week more, and if it won't happen again, I think we can close it.

**Comment by mfc** [comment]
still happening to me at least, with latest firefox 109.0 in fedora-36. in the past had hardware acceleration disabled, i have also recently tried with `Use recommended performance settings`, no difference i can tell.

now i can at least close the VM that firefox is frozen within cleanly, in the past i had to kill the VM.

**Comment by the-moog** [comment]
I've submitted [#8145 ](https://github.com/QubesOS/qubes-issues/issues/8145#issue-1669623291) that may be a way to demonstrate a root cause of at least one mechanism for ranom freezes

**Comment by ziplantil** [comment]
I've had numerous problems like this on Fedora XFCE across multiple Fedora and Firefox versions. These are some observations I've had:

* The longest issue has something to do with dragging tabs - I'm not sure exactly what it is, but dragging a tab in a specific way can cause it to get stuck halfway - but trying to drag it again fixes it. If you don't fix it, you cannot switch between tabs correctly - the UI won't update.
* A similar issue like the above can also occur except the tab does not get visually stuck halfway between tabs - this is more insidious. The UI won't update when you open a new tab, click on a tab, etc., but the title bar will. This seems to have something to do with dragging the tab down (?). I thought for quite some time that this could only be fixed by restarting the browser, but I eventually found that dragging tabs solves this one too.

More recently though I've been having more issues:
* At times, Firefox goes into on-off massive input lag mode, where most keyboard inputs are delayed by around 15 seconds, if not more. If this happens, sometimes it starts working again after a while, only to relapse back into input lag. Some inputs, like hotkeys (such as to open a new tab), keep working fine during this time.
* Other times the browser simply freezes completely. Minimizing and maximizing the window will cause artifacts akin to the thread not drawing anything into the 'new' window region.

These are frustrating and seem to happen at complete random. I have not found a single way to reproduce any of these reliably.

**Comment by Warthog-Capital** [comment]
Just wanted to add that I haven't encountered this issue for several months now. From my side it can be closed.

**Comment by na--** [comment]
I still encounter it, but much more rarely than before, and I think it's a smaller version of the original bug :confused: 

Very rarely, a single Firefox window freezes (others from the same session are fine), but it's mostly the borwser chrome part that's frozen (the interface), not the actual content :man_shrugging: And even the interface is somewhat responsive, e.g. I can switch to the next tab (Ctrl+Tab), and if I switch to another window and back to the frozen window (e.g. 2x Alt+Tab), I see the contents of the new tab, as @ziplantil mentioned. But contrary to the original report in the issue, I usually can interact with the page contents and even scroll. I can also blindly copy the address bar contents (Ctrl+L, Ctrl+C) successfully and open the same tabs in another window... :sweat_smile: 

At this point, I have no indications if this is QubesOS specific or not, but trying to search for it just leads me back to this issue, I can't find anything similar at https://bugzilla.mozilla.org/ (though I may not be searching it very well). So it might be a Firefox bug that only surfaces on QubesOS, which makes keeping the issue open somewhat worth it :man_shrugging:

**Comment by the-moog** [comment]
[@na--](https://github.com/na--) Can you confirm if the logs show any hint of an OOM occurring at the time you get a frozen dialog? Look in two places, both in the app Qube and in DOM0, (or whatever domain hosts your GUI). 
I've found you can have two instances of an app (e.g. FF) open and one is dead and the other not, depends what got killed as the app UI is separate from the app itself. i.e. An app/process/thread can die but the GUI objects remain on the screen.  The container level UI objects usually still work.  You can click, move, resize, minimize but you can't close them and their contents is either empty or won't update.  I've also seen similar in DOM0, where the result is an unresponsive dialog, not always in the app that you are using.

**Comment by na--** [comment]
:thinking: I don't remember seeing any signs of an OOM, but I haven't actually explicitly looked, I'll make sure to do so next time it happens! It's unlikely because the VM I most often encounter the problem has 6GB of RAM, but it's not impossible... That said, it happens very, very rarely nowadays, so it might be a while until I have more information.

**Comment by the-moog** [comment]
Only 6G? Mine has 32G and it still manages it, though rarely now I've made some adjustments.
It seems Xen is not that efficient with memory and the stock Qubes images have defaults for important IPC between DOM0 and appQubes are set to run with the same 'kill me' badge as a toy app or occasional cron.

Does your GPU eat into CPU DRAM?

The appVM I am trying in right now has 12G allocated with 12G swap.  It has 7G free but not started swapping.  So 5G used and I have only three apps open. One window of FF open with 8 tabs, a terminal (in which I just typed `free`) and Dolphin. 

DOM0 (also my GUI) has 4G allocated.  81Mb free (eeek - need to fix that) No apps running other than X and the display manager.  Top says the display manager is a hog.

**Comment by Warthog-Capital** [comment]
After the most recent Firefox update (115.3.0esr) on Debian 11, the problem started occurring again for me. Three times today. Restarting the browser still solves the problem, until the next time.

**Comment by the-moog** [comment]
The proper solution is to make anything related to the Qube graphics/UI pipe, and Qube/Xen interaction/management less prone to being taken out by OOM Killer.  Currently it seems to use the software precision of a blunderbuss. Most things have the same values (see top) I tweaked a few apps by altering their startup in systemd, and giving them a better OOM value, but there are a lot and I don't know what half of them do. That seemed to help but I too have recently been seeing a few more frequent lockups. Plus, of course DOM0 can run/close/restart any app on any cube at any time, so those need to be protected if they are critical, and a failure would leave he Qube in a zombie state.  Especially if they are non-atomic.

**Comment by marmarek** [comment]
The comments above clearly says it is _not_ OOM... And if that would be OOM killing some qubes graphic component, restarting browser wouldn't work.

**Comment by mfc** [comment]
for [my issue](https://github.com/QubesOS/qubes-issues/issues/7695#issuecomment-1410535897) (which may be orthogonal to OP issue), it requires killing the qube. not only can i not restart the browser, i cannot shut down (or restart) the qube cleanly.

**Comment by DemiMarie** [comment]
@mfc can you file a separate ticket for that?

**Comment by mfc** [comment]
sure, you're right it is different issue. lemme first migrate to R4.2.0 from R4.1.2 and see if it still occurs and if so i'll make an issue

**Comment by DemiMarie** [comment]
R4.1 is still supported, so even a bug that was fixed in R4.2 would still be valid.

**Comment by the-moog** [comment]
> The comments above clearly says it is _not_ OOM... And if that would be OOM killing some qubes graphic component, restarting browser wouldn't work.

Closing the browser frees up memory and if you are lucky systemd sometimes restarts the killed services. I once left it an entire day and then suddenly is sprung back into life as though nothing has happened.

As I am sure you know there is a message bus  between dom0 and each appVM. Depending on which bits are still working you may or may not get various messages across, same true for graphics and network.  E.g. commands for shutdown or interlocks round that may never arrive.  Yes Xen can just pull the process, but that's all. I've found some tricks inside the Xen low level tools that allow you to make a direct virtual serial console login (as though you'd just plugged in an RS232 cable) and with that I've been able to (sometimes) see this going on. I managed to use SRQ once too. What I often see is systemd restarting processes so fast even that does not work. 100% of the CPU is just creating and killing processes.  Or, processes starting, then crashing as some resource is missing then starting again.  Or two processes killing each other in turn through the OOM. When it does these things it takes like 5 mins to echo one character, if at all.  When it's one of the Utility Qubes that is effected (e.g. net/usb/graphics/sound) then often any attempts to investigate it are often borked at the start. 
Sometime it even affects dom0, with it desperately trying to recover and restore message paths, but you end up with what we used to call 'glaring' in telecoms.  Where both ends are in a mutually entangled loop that neither will give up on and you can't fix it as the mechanism to do that is the thing that is within the system that's broken.

**Comment by DemiMarie** [comment]
@the-moog what would be needed to prevent this?

I’m seriously considering disabling the OOM killer for the GUI agent and for anything that needs to be running for `qvm-console-dispvm` to work.  If there really is not enough memory to run these, I suspect it is usually better to just panic and reboot.

**Comment by UndeadDevel** [comment]
Affects 4.2.

I've also been seeing this, but rarely, maybe once every two weeks or so and only with "normal" Firefox, not with Tor Browser IIRC. I have never seen this on baremetal Fedora (GNOME), despite that machine having had a very low amount of RAM that often was used to its limits.

**Comment by 9ao9ai9ar** [comment]
I also encountered this issue today on Firefox 125.0 inside an AppVM with 16 GB of memory based on the Fedora 38 GNOME template for Qubes OS 4.2.1. In addition to the input lags mentioned by [@ziplantil](https://github.com/QubesOS/qubes-issues/issues/7695#issuecomment-1546998087), which does not seem to affect other programs like the terminal, over half of the CJK characters inside YouTube captions are missing fonts despite having them installed manually and working before. I am trying out a fix discussed in [this Reddit post](https://www.reddit.com/r/firefox/comments/p8g5zd/why_does_disabling_accessibility_services_improve/), setting `accessibility.force_disabled` to `1` in `about:config`, to reduce Firefox's memory footprint and see if this issue ever reappears again.

**Comment by neoniobium** [comment]
For me this accrues rather infrequent on `Firefox` and `Torbrowser`. I never have this happen with a `Chrome`-derivat however. For me it affects `Debian-12` and `Fedora-40` alike. Since `Debian` was mentioned before too, I suggest updating the labels and maybe issue name to something like `Firefox based Browser...` because `Torbrowser` is also affected.

**Comment by ben-grande** [comment]
Can someone please retest on R4.3 to know if it needs the "Affects 4.3" label?

**Comment by jamke** [comment]
I do not have it on R4.3.

**Comment by andrewdavidwong** [comment]
Closing as completed. If anyone believes this issue is not yet completed, or if anyone is still affected by this issue, please leave a comment saying so, and we'll be happy to reopen it. Thank you.
