### ISSUE TITLE
All qubes frozen after resuming from suspend on Librem 14

### ISSUE THREAD

**Issue by ihateprogramming88** [QubesOS/qubes-issues#8061]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release (if applicable)

xen_version : 4.14.5
linux 6.1.7-1.fc32.qubesx86_64

### Brief summary
Once the laptop is suspended (librem14) and come to resume work later, all the qubes are frozen, need to kill all qubes or restart to continue. Not sure if librem related or not.

**Comment by euidzero** [comment]
I noticed it and this seems related to the vm kernel. With 5.18.16-1.fc32.qubes.x86_64 the resume works. With 6.X it freeze when resuming.

**Comment by viq** [comment]
Possibly related to https://github.com/QubesOS/qubes-issues/issues/8139

**Comment by viq** [comment]
I'm seeing something I think similar, and I'll expand on what I've seen and tried:
Qubes 4.1, dom0 running kernel `5.15.103-1`, VMs running `6.3.2-1`. Most templates running Fedora 37 unless specifically noted. Dell Latitude 7490.

After suspending and unsuspending, most VMs (both AppVMs and DispVMs) are either completely non-responsive (fedora), or will for example open new terminal window, but the terminal window will not draw properly, and while e.g. exiting tor browser in whonix DispVM may work, the terminals don't do anything, including exiting. Except `sys-net` and `sys-usb`, which are fully functional (except usual USB weirdness of `sys-usb`, but that's a separate issue).

After some testing, commonalities were found:
- both debian 11 and whonix VMs will open such non-functional terminal after unsuspending
- machines in `pvh` mode will display the above issues, whereas machines in `hvm` mode (both debian and fedora) will continue working properly after unsuspend

Also, attempting to suspend while having such non-functional VMs just waits for something regarding them. When I tried killing them all, immediately after last of them died the machine suspended, and crashed when trying to unsuspend :shrug:

**Comment by na--** [comment]
I noticed very similar issues on an MSI laptop with an 11th gen Intel CPU. My suspend had been completely non-functional for a while, I'd basically given up on having working sleep/suspend with QubesOS on recent hardware :sweat_smile: But my hardware is no longer that recent, so I decided to give it one more try and following [this advice from the docs](https://www.qubes-os.org/doc/suspend-resume-troubleshooting/#suspend-turns-off-the-screen-and-gets-stuck), I added the `mem_sleep_default=deep` option and it seemed like sleep was finally working! :tada: But then I noticed a few minor problems that are already mentioned here and one major problem that hasn't been mentioned so far...

In my case, the used kernel was `6.3.9`, in both dom0 and in all VMs. With the `mem_sleep_default=deep` option, the laptop finally goes to sleep and successfully wakes up, but as @viq has experienced, all `pvh` VMs were frozen on resume. Fortunately, all `hvm` VMs were working just fine, even after several suspend and resume cycles :tada:

Decided to try using all of my installed VM kernels and `pvh` VMs resume successfully with kernels `5.15.103`, `6.1.26`, `6.1.28`, `6.1.35`, and `6.2.10`. And `pvh` VMs don't resume correctly and are frozen with VM kernels `6.3.2` and `6.3.9`. These frozen VMs can't even be shut down normally and I have to kill them with `qvm-kill` from dom0. During all of these experiments, dom0 and `hvm` VMs like `sys-net` and `sys-usb` were all using kernel `6.3.9` and resuming without a hitch, so it seems like the 6.3.x kernel releases have some sort of a regression only for `pvh` VMs :confused:

If that was all, I could get by on the 6.2 kernel for now and have fully working resume, but I noticed another problem that doesn't seem mention here. Even after disabling the CPU hyper-threading from my BIOS, [as instructed here](https://www.qubes-os.org/doc/suspend-resume-troubleshooting/#power-consumption-increases-on-suspendresume), I noticed that my laptop is sluggish and that my power consumption after resuming is roughly doubled compared to before the suspend. I measured it with a power meter and if I am pulling 25-35 watts before suspending, the laptop starts consuming 60-75 watts after resuming, even when idle :confused: It also seems perceptibly more sluggish, with perceptible lag when typing or switching windows. 

Any ideas what could be the cause of that problem and what I could do to ameliorate it?

**Comment by na--** [comment]
FWIW, running dom0 with kernel `6.2.10` doesn't help with the post-resume power consumption spike :disappointed: Neither does disabling the "CPU C-states" from the BIOS. 

Also, given the information in https://github.com/QubesOS/qubes-issues/issues/5210, it seems like that was an old issue that should have been fixed in the current Xen version :confused:

**Comment by na--** [comment]
I just tested the latest kernel `6.4.8-1` and the system resumed successfully with it in both dom0 and the VMs :tada: I guess the `6.3.x` kernels were the only problematic ones :man_shrugging: 

Unfortunately, the higher power usage after resume is still a problem :disappointed: Though, given that the power usage problem is tracked in https://github.com/QubesOS/qubes-issues/issues/5210, I think this issue can now be closed?

**Comment by euidzero** [comment]
Not yet fixed there with kernel 6.4.8-1

 - if the VM has no open windows NOR notification icon on the xfce panel then the (fedora-37 based) VM resumes correctly from suspend. 
 - if there anything displayed by the VM at suspend time then resume failed : The VM is unresponsive. I cannot shut it down. Must be killed
 - Debian 11 based VM are unaffected

**Comment by euidzero** [comment]
Got it (triple checked) : the issue is with the kernel opt : clocksource=tsc. A VM with this option does not resume. I was confused because not all my VM use the same kernel options.
